[aws]
app-machine ansible_host=98.84.74.9 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/multi-cloud-key.pem

[azure]
azure-vm ansible_host=20.102.80.106 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure-vm-key.pem
